CREATE TABLE GALLERY(GID VARCHAR(20) PRIMARY KEY,GNAME CHAR(20),LOCATION CHAR(20));
 CREATE TABLE EXHIBITION (EID VARCHAR(20) PRIMARY KEY, GID VARCHAR(20), STARTDATE DATE, ENDDATE DATE, FOREIGN KEY(GID) REFERENCES GALLERY(GID) 
 ON  DELETE CASCADE);
CREATE TABLE ARTWORK(ARTID VARCHAR(20) PRIMARY KEY,TITLE VARCHAR(20),YEAR INT,
    TYPE_OF_ART VARCHAR(20),
    PRICE INT,
    EID VARCHAR(20),
    GID VARCHAR(20),
    ARTISTID VARCHAR(20));
    CREATE TABLE CUSTOMER
              (CUSTID VARCHAR(20) PRIMARY KEY,
             GID VARCHAR(20),
             ARTID VARCHAR(20),
             FNAME1 CHAR(20),
             LNAME1 CHAR(20),
             DOB DATE,
             ADDRESS CHAR(20));
			CREATE TABLE ARTIST
(ARTISTID VARCHAR(20)PRIMARY KEY,
GID VARCHAR(20),
CUSTID VARCHAR(20),
EID VARCHAR(20),
FNAME CHAR(20),
LNAME CHAR(20),
BIRTHLACE CHAR(20),
STYLE CHAR(20));
CREATE TABLE CONTACT
(CUSTID VARCHAR(20),
PHONE VARCHAR(12));





 
